### ISSUE TITLE
在正在获取个人信息那里卡住了

### ISSUE THREAD

**Issue by DponXiaodong** [Tishacy/ZJU-nCov-Hitcarder#10]
\ 正在获取个人信息...Job "main (trigger: cron[hour='17', minute='9'], next run at: 2020-03-28 17:09:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "F:\azb\ZJU-nCov-Hitcarder-master (3)\ZJU-nCov-Hitcarder-master\daka.py", line 88, in main
    dk.get_info()
  File "F:\azb\ZJU-nCov-Hitcarder-master (3)\ZJU-nCov-Hitcarder-master\daka.py", line 49, in get_info
    old_info = json.loads(re.findall(r'oldInfo: ({[^}]+})', html)[0])
IndexError: list index out of range
\ 正在获取个人信息...

**Comment by saberPanDraGon** [comment]
5555 出新的选项了 大大快更新（催更警告

**Comment by Tishacy** [comment]
> 5555 出新的选项了 大大快更新（催更警告

已更新到最新的表单啦

**Comment by saberPanDraGon** [comment]
> > 5555 出新的选项了 大大快更新（催更警告
> 
> 已更新到最新的表单啦

谢谢谢谢

**Comment by saberPanDraGon** [comment]
更新完之后出现和上面那位一样的错误（挠头
