### ISSUE TITLE
关于编码形式的问题

### ISSUE THREAD

**Issue by IIIIMortal** [Tishacy/ZJU-nCov-Hitcarder#28]
俺搬运到服务器上的时候出现了如下报错，冲浪了一下说是默认编码的问题，请问如何解决？（在wsl上能跑，但是搬到cent os的时候就不行了————
```
Traceback (most recent call last):
  File "hitcarder.py", line 196, in <module>
    main(username, password, delay)
  File "hitcarder.py", line 147, in main
    print("\U0001f68c \u6253\u5361\u4efb\u52a1\u542f\u52a8")
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/site-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f68c' in position 0: ordinal not in range(128)
```

**Comment by IIIIMortal** [comment]
`ð¦
â   ä»å¤©å·²ç»å¡«æ¥äº
â° å·²åå¨ä¸ºæ¨æå
â ¹ æ­£å¨ä¸ºæ¨æå
â  æ­£å¨ä¸ºæ¨æå
â 3190102182 ä½å®æå¨ä¸ºæ¨æå
[Sta¡ä»»å¡å¨æ°å»ºæå6-01 11:11:58
ð æå
`

**Comment by IIIIMortal** [comment]
现在就是运行的时候会出现
![image](https://user-images.githubusercontent.com/56387269/120261860-5713d800-c2cb-11eb-9c49-65c4b52aa0c1.png)

**Comment by IIIIMortal** [comment]
重新拉了一下源码 已解决
