### ISSUE TITLE
一直在获取个人信息

### ISSUE THREAD

**Issue by Matao258** [Tishacy/ZJU-nCov-Hitcarder#7]
你好 我在运行的时候一直在获取个人信息
python版本是3.7
系统是centos
不知道咋回事
系统显示如下 
账号密码没有问题
`⠹ 正在获取个人信息...Job "main (trigger: cron[hour='15', minute='48'], next run                                                                                                                                                              at: 2020-02-14 15:48:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/sbin/python-3.7/lib/python3.7/site-packages/apscheduler/execu                                                                                                                                                             tors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "daka.py", line 82, in main
    dk.get_info()
  File "daka.py", line 49, in get_info
    old_info = json.loads(re.findall(r'oldInfo: ({[^}]+})', html)[0])
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/__init__.py", line 348, in                                                                                                                                                              loads
    return _default_decoder.decode(s)
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/decoder.py", line 337, in                                                                                                                                                              decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/decoder.py", line 353, in                                                                                                                                                              raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 458                                                                                                                                                              (char 457)
⠏ 正在获取个人信息...`

**Comment by Tishacy** [comment]
JSONDecodeError是json数据解析错误，你在代码第49行`old_info = json.loads(re.findall(r'oldInfo: ({[^}]+})', html)[0])`下面加一行`print(re.findall(r'oldInfo: ({[^}]+})', html)[0])`，看一下是字符串哪个字符解析错误。

也有可能是网络原因导致response没拿到完整的返回值，可以多试几次。
